name: SplitEase CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # 3. Build Docker Image
      - name: Build Docker image
        run: docker build -t atulranadev/splitease:latest .

      # 4. Push Docker Image
      - name: Push Docker image
        run: docker push atulranadev/splitease:latest

      # 5. Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull atulranadev/splitease:latest

            docker stop splitease || true
            docker rm splitease || true

            docker run -d --name splitease \
              -p 8080:8080 \
              --network split-network \
              -e SERVER_PORT=8080 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e JWT_EXPIRY=36000000 \
              -e MAIL_HOST=smtp.gmail.com \
              -e MAIL_PORT=587 \
              -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
              -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              -e MAIL_FROM=help.splitease@gmail.com \
              -e MAIL_FROM_NAME=SplitEase \
              -e BACKEND_URL=${{ secrets.BACKEND_HOST_DOMAIN }} \
              -e FRONTEND_URL=${{ secrets.FRONTEND_HOST_DOMAIN }} \
              atulranadev/splitease:latest
